### ISSUE TITLE
[MSHARED-997] Failed / error test DefaultProjectDependencyAnalyzerTest in maven-dependency-analyzer

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-dependency-analyzer#202]
**[Slawomir Jaranowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slawekjaranowski)** opened **[MSHARED-997](https://issues.apache.org/jira/browse/MSHARED-997?redirect=false)** and commented

There is no possibility to build project by:

```java
mvn clean verify
```

Tested last commit: `b6adba0bcda5036a9bc59e23be2976672b729198`

Maven and java versin:

```java
Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)
Maven home: /usr/local/Cellar/maven/3.8.2/libexec
Java version: 1.8.0_302, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk@8/1.8.0+302/libexec/openjdk.jdk/Contents/Home/jre
```

I have many logs like:

```java
37) No implementation for java.util.Set<org.eclipse.aether.spi.localrepo.LocalRepositoryManagerFactory> was bound.
  while locating java.util.Set<org.eclipse.aether.spi.localrepo.LocalRepositoryManagerFactory>
    for parameter 0 at org.eclipse.aether.internal.impl.DefaultLocalRepositoryProvider.<init>(Unknown Source)
  while locating org.eclipse.aether.internal.impl.DefaultLocalRepositoryProvider
  at ClassRealm[plexus.core, parent: null]
  at ClassRealm[plexus.core, parent: null]
  while locating org.eclipse.aether.impl.LocalRepositoryProvider
    for parameter 8 at org.eclipse.aether.internal.impl.DefaultRepositorySystem.<init>(Unknown Source)
  while locating org.eclipse.aether.internal.impl.DefaultRepositorySystem
  at ClassRealm[plexus.core, parent: null]
  at ClassRealm[plexus.core, parent: null]
  while locating org.eclipse.aether.RepositorySystem
  while locating org.apache.maven.artifact.resolver.DefaultArtifactResolver
  at ClassRealm[plexus.core, parent: null]
  at ClassRealm[plexus.core, parent: null]
```

and test result:

```java
INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   DefaultProjectDependencyAnalyzerTest.setUp:81->PlexusTestCase.lookup:199 » ComponentLookup
[ERROR]   DefaultProjectDependencyAnalyzerTest.setUp:81->PlexusTestCase.lookup:199 » ComponentLookup
[ERROR]   DefaultProjectDependencyAnalyzerTest.setUp:81->PlexusTestCase.lookup:199 » ComponentLookup
[ERROR]   DefaultProjectDependencyAnalyzerTest.setUp:81->PlexusTestCase.lookup:199 » ComponentLookup
[ERROR]   DefaultProjectDependencyAnalyzerTest.setUp:81->PlexusTestCase.lookup:199 » ComponentLookup
[ERROR]   DefaultProjectDependencyAnalyzerTest.setUp:81->PlexusTestCase.lookup:199 » ComponentLookup
[ERROR]   DefaultProjectDependencyAnalyzerTest.setUp:81->PlexusTestCase.lookup:199 » ComponentLookup
[ERROR]   DefaultProjectDependencyAnalyzerTest.setUp:81->PlexusTestCase.lookup:199 » ComponentLookup
[ERROR]   DefaultProjectDependencyAnalyzerTest.setUp:81->PlexusTestCase.lookup:199 » ComponentLookup
[ERROR]   DefaultProjectDependencyAnalyzerTest.setUp:81->PlexusTestCase.lookup:199 » ComponentLookup
[ERROR]   DefaultProjectDependencyAnalyzerTest.setUp:81->PlexusTestCase.lookup:199 » ComponentLookup
[ERROR]   DefaultProjectDependencyAnalyzerTest.setUp:81->PlexusTestCase.lookup:199 » ComponentLookup
[ERROR]   DefaultProjectDependencyAnalyzerTest.setUp:81->PlexusTestCase.lookup:199 » ComponentLookup
[ERROR]   DefaultProjectDependencyAnalyzerTest.setUp:81->PlexusTestCase.lookup:199 » ComponentLookup
[ERROR]   DefaultProjectDependencyAnalyzerTest.setUp:81->PlexusTestCase.lookup:199 » ComponentLookup
[INFO] 
[ERROR] Tests run: 101, Failures: 0, Errors: 15, Skipped: 0
```

### Build on Apache Jenkins

There is also strange behavior that `jenkins` build also has similar errors - but failed tests aren't reported.

https://ci-maven.apache.org/job/Maven/job/maven-box/job/maven-dependency-analyzer/job/master/

### Build on GitHub

There is also the same problem on GitHub:

 https://github.com/apache/maven-dependency-analyzer/actions

---

**Issue Links:**
- [MSHARED-916](https://issues.apache.org/jira/browse/MSHARED-916) Require Maven 3.2.5+ (drop dependency to Maven 2.0.5)

**Remote Links:**
- [GitHub Pull Request #45
](https://github.com/apache/maven-dependency-analyzer/pull/45)

**Comment by jira-importer** [comment]
**[Slawomir Jaranowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slawekjaranowski)** commented

with commit `a79910e73809f45c6cba473d87f880012be7146e`

and maven `3.8.2` we have:

 

```java
[ERROR] testJarWithRuntimeScopedTestDependency(org.apache.maven.shared.dependency.analyzer.DefaultProjectDependencyAnalyzerTest)  Time elapsed: 0.018 s  <<< ERROR!
org.apache.maven.shared.test.plugin.TestToolsException: Error building Maven settings.
        at org.apache.maven.shared.dependency.analyzer.DefaultProjectDependencyAnalyzerTest.setUp(DefaultProjectDependencyAnalyzerTest.java:86)
Caused by: org.codehaus.plexus.util.xml.pull.XmlPullParserException: Unrecognised tag: 'blocked' (position: START_TAG seen ...</url>\r\n      <blocked>... @164:16) 
        at org.apache.maven.shared.dependency.analyzer.DefaultProjectDependencyAnalyzerTest.setUp(DefaultProjectDependencyAnalyzerTest.java:86)
```

**Comment by jira-importer** [comment]
**[Piotr Zygielo](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pzygielo)** commented

For that reason (Unrecognised tag: 'blocked') I've used maven 3.3.9 to build other commits. And 15150191 is the first one to fail with `... ComponentLookup`.
