### ISSUE TITLE
[MSHARED-1398] StringIndexOutOfBoundsException processing record classes

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-dependency-analyzer#230]
**[Jared Stehler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jstehler)** opened **[MSHARED-1398](https://issues.apache.org/jira/browse/MSHARED-1398?redirect=false)** and commented

Processing classes with records results in an index out of bounds exception:

```java
Caused by: java.lang.StringIndexOutOfBoundsException: Index 41 out of bounds for length 41
	at java.base@21.0.3/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base@21.0.3/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base@21.0.3/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base@21.0.3/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base@21.0.3/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base@21.0.3/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base@21.0.3/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base@21.0.3/java.lang.String.checkIndex(String.java:4832)
	at java.base@21.0.3/java.lang.StringLatin1.charAt(StringLatin1.java:46)
	at java.base@21.0.3/java.lang.String.charAt(String.java:1555)
	at app//org.objectweb.asm.Type.getReturnTypeOffset(Type.java:378)
	at app//org.objectweb.asm.Type.getReturnType(Type.java:355)
	at app//org.apache.maven.shared.dependency.analyzer.asm.ResultCollector.addMethodDesc(ResultCollector.java:112) 
```

I have a reproducible test case here: https://github.com/jaredstehler/maven-dependency-analyzer/tree/js-repro-record-error

---

**Affects:** maven-dependency-analyzer-1.14.0

**Issue Links:**
- [MSHARED-1347](https://issues.apache.org/jira/browse/MSHARED-1347) maven-dependency-plugin ignores class of object passed as a parameter to method references

- [MSHARED-1393](https://issues.apache.org/jira/browse/MSHARED-1393) Allow to exclude classes from verification - revert MSHARED-1248

**Remote Links:**
- [GitHub Pull Request #121
](https://github.com/apache/maven-dependency-analyzer/pull/121)

**Comment by jira-importer** [comment]
**[Slawomir Jaranowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slawekjaranowski)** commented

Thanks for reporting .... I was dropped a simply catch such exception in https://github.com/apache/maven-dependency-analyzer/pull/118

But you can skip problematic classes from analizes

I will check where is the root of cause - maybe we should report in to ASM.

**Comment by jira-importer** [comment]
**[Jared Stehler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jstehler)** commented

I did create a repo for reporting to ASM: https://github.com/jaredstehler/asm-issues/blob/main/src/main/java/com/jaredstehler/scratch/asm/issues/InvalidTypeDescriptor.java

**Comment by jira-importer** [comment]
**[Jared Stehler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jstehler)** commented

created https://github.com/apache/maven-dependency-analyzer/pull/121 with the failing test

**Comment by jira-importer** [comment]
**[Slawomir Jaranowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slawekjaranowski)** commented

[Jared Stehler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jstehler) - fixed you can check my last commit to PR
